In [1]:
import pandas as pd

# Load raw time series data

In [2]:
path = "../../data/time_series_60min_singleindex.csv"
df = pd.read_csv(path)

df.head()

,utc_timestamp,cet_cest_timestamp,AT_load_actual_entsoe_transparency,AT_load_forecast_entsoe_transparency,AT_price_day_ahead,AT_solar_generation_actual,AT_wind_onshore_generation_actual,BE_load_actual_entsoe_transparency,BE_load_forecast_entsoe_transparency,BE_solar_generation_actual,...,SI_load_actual_entsoe_transparency,SI_load_forecast_entsoe_transparency,SI_solar_generation_actual,SI_wind_onshore_generation_actual,SK_load_actual_entsoe_transparency,SK_load_forecast_entsoe_transparency,SK_solar_generation_actual,SK_wind_onshore_generation_actual,UA_load_actual_entsoe_transparency,UA_load_forecast_entsoe_transparency
0,2014-12-31T23:00:00Z,2015-01-01T00:00:00+0100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-01T00:00:00Z,2015-01-01T01:00:00+0100,5946.0,6701.0,35.0,NaN,69.0,9484.0,9897.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-01T01:00:00Z,2015-01-01T02:00:00+0100,5726.0,6593.0,45.0,NaN,64.0,9152.0,9521.0,NaN,...,1045.47,816.0,NaN,1.17,2728.0,2860.0,3.8,NaN,NaN,NaN
3,2015-01-01T02:00:00Z,2015-01-01T03:00:00+0100,5347.0,6482.0,41.0,NaN,65.0,8799.0,9135.0,NaN,...,1004.79,805.0,NaN,1.04,2626.0,2810.0,3.8,NaN,NaN,NaN
4,2015-01-01T03:00:00Z,2015-01-01T04:00:00+0100,5249.0,6454.0,38.0,NaN,64.0,8567.0,8909.0,NaN,...,983.79,803.0,NaN,1.61,2618.0,2780.0,3.8,NaN,NaN,NaN

# Extract countries

In [ ]:
countries = set(c[:2].upper() for c in df.columns if "timestamp" not in c) # Create set of countries (no duplicates)
countries.remove("GB")
countries.add("GB_GBN") # GB column is actually GB_GBN
countries = list(countries)
countries.sort()
print("|".join(countries))

AT|BE|BG|CH|CY|CZ|DE|DK|EE|ES|FI|FR|GB_GBN|GR|HR|HU|IE|IT|LT|LU|LV|ME|NL|NO|PL|PT|RO|RS|SE|SI|SK|UA

# Filter only timestamp column and load columns

In [4]:
filtered_columns = ["utc_timestamp"] + [f'{c}_load_actual_entsoe_transparency' for c in countries]
df = df[filtered_columns]
df.rename(columns={"GB_GBN_load_actual_entsoe_transparency": "GB_load_actual_entsoe_transparency"}, inplace=True)
df.head()

,utc_timestamp,AT_load_actual_entsoe_transparency,BE_load_actual_entsoe_transparency,BG_load_actual_entsoe_transparency,CH_load_actual_entsoe_transparency,CY_load_actual_entsoe_transparency,CZ_load_actual_entsoe_transparency,DE_load_actual_entsoe_transparency,DK_load_actual_entsoe_transparency,EE_load_actual_entsoe_transparency,...,NL_load_actual_entsoe_transparency,NO_load_actual_entsoe_transparency,PL_load_actual_entsoe_transparency,PT_load_actual_entsoe_transparency,RO_load_actual_entsoe_transparency,RS_load_actual_entsoe_transparency,SE_load_actual_entsoe_transparency,SI_load_actual_entsoe_transparency,SK_load_actual_entsoe_transparency,UA_load_actual_entsoe_transparency
0,2014-12-31T23:00:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-01T00:00:00Z,5946.0,9484.0,NaN,NaN,NaN,NaN,41151.0,NaN,NaN,...,9401.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-01T01:00:00Z,5726.0,9152.0,4585.0,7640.14,NaN,5957.57,40135.0,3100.02,764.7,...,8957.0,15104.99,13979.46,5123.9,NaN,NaN,14485.0,1045.47,2728.0,NaN
3,2015-01-01T02:00:00Z,5347.0,8799.0,4440.0,7391.44,NaN,5878.87,39106.0,2980.39,749.8,...,8462.0,14882.56,13453.78,4771.1,NaN,NaN,14298.0,1004.79,2626.0,NaN
4,2015-01-01T03:00:00Z,5249.0,8567.0,4418.0,7332.57,NaN,5827.80,38765.0,2933.49,746.5,...,8156.0,14755.09,13306.00,4443.5,NaN,NaN,14249.0,983.79,2618.0,NaN